version: "3.9"
services:
    nodeserver:
      image: node
      build:
          context: ./app
      ports:
          - "5000:5000"
    nginx:
      image: nginx
      restart: always
      build:
        context: ./nginx
      ports:
        - "80:80"